name: email-worker
namespace: workers

image:
  repository: jukpozi/emailservice
  tag: latest
  pullPolicy: Always

serviceAccount:
  name: emailservice-worker-sa
  clientId: "5128d644-0463-4e9d-bad8-fa2d26882f89"

env:
  - name: WORKER_MODE
    value: "true"
  - name: SERVICEBUS_NAMESPACE
    value: "sre-sb-namespace"
  - name: SERVICEBUS_TOPIC
    value: "checkout-events"
  - name: SERVICEBUS_SUBSCRIPTION
    value: "email"
  - name: DISABLE_PROFILER
    value: "1"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://otel-collector-opentelemetry-collector.observability.svc.cluster.local:4317"
  - name: OTEL_SERVICE_NAME
    value: "email-worker"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

keda:
  serviceBusNamespace: sre-sb-namespace
  topicName: checkout-events
  subscriptionName: email
  messageCount: "1"
  pollingInterval: 10
  cooldownPeriod: 60
  minReplicaCount: 0
  maxReplicaCount: 8
