apiVersion: v1
kind: ServiceAccount
metadata:
  name: shippingservice-worker-sa
  namespace: workers
  annotations:
    azure.workload.identity/client-id: "<MANAGED_IDENTITY_CLIENT_ID>"
  labels:
    azure.workload.identity/use: "true"
