name: cartservice-worker
namespace: workers

image:
  repository: jukpozi/cartservice-worker
  tag: latest
  pullPolicy: Always

serviceAccount:
  name: cartservice-worker-sa
  clientId: "546eacdf-f31f-4950-9319-73a6ce56713c"

env:
  - name: CARTSERVICE_URL
    value: "http://cartservice.core.svc.cluster.local:7070"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

keda:
  serviceBusNamespace: sre-sb-namespace
  topicName: business-events
  subscriptionName: cartservice-sub
  messageCount: "5"
  pollingInterval: 10
  cooldownPeriod: 60
  minReplicaCount: 0
  maxReplicaCount: 10
