apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingassistantservice-worker
  namespace: workers
spec:
  replicas: 0   # KEDA controls replicas
  selector:
    matchLabels:
      app: shoppingassistantservice-worker
  template:
    metadata:
      labels:
        app: shoppingassistantservice-worker
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: shoppingassistantservice-worker-sa
      containers:
        - name: shoppingassistantservice-worker
          # TODO: pin to a specific tag e.g. jukpozi/shoppingassistantservice-worker:1.0.0
          image: jukpozi/shoppingassistantservice-worker:latest
          imagePullPolicy: Always
          env:
            - name: SHOPPINGASSISTANTSERVICE_URL
              value: "http://shoppingassistantservice.core.svc.cluster.local:8080"
            - name: NERVE_CENTER_URL
              value: "http://nerve-center.core.svc.cluster.local:8080"
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
