apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: shoppingassistantservice-worker-scaledobject
  namespace: workers
spec:
  scaleTargetRef:
    name: shoppingassistantservice-worker
  pollingInterval: 15
  cooldownPeriod: 120
  minReplicaCount: 0
  maxReplicaCount: 3
  triggers:
    - type: azure-servicebus
      metadata:
        namespace: sre-sb-namespace
        topicName: business-events
        subscriptionName: shoppingassistant-sub
        messageCount: "1"
      authenticationRef:
        name: shoppingassistantservice-worker-trigger-auth
