apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sre-platform
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/jaeveloper/sre-proj-upgrade
    targetRevision: main
    path: kubernetes-platform/argocd/apps

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
