name: paymentservice
namespace: core

replicaCount: 1

image:
  repository: jukpozi/paymentservice
  tag: latest
  pullPolicy: Always

serviceAccount:
  name: paymentservice-sa

containerPort: 50051

service:
  type: ClusterIP
  port: 50051

resources:
  requests:
    cpu: "100m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

env:
  - name: PORT
    value: "50051"
  - name: DISABLE_TRACING
    value: "0"
  - name: DISABLE_PROFILER
    value: "1"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://otel-collector.observability.svc.cluster.local:4317"
  - name: OTEL_SERVICE_NAME
    value: "paymentservice"
