apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice-worker
  namespace: workers
spec:
  replicas: 0   # KEDA controls replicas
  selector:
    matchLabels:
      app: currencyservice-worker
  template:
    metadata:
      labels:
        app: currencyservice-worker
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: currencyservice-worker-sa
      containers:
        - name: currencyservice-worker
          # TODO: pin to a specific tag e.g. jukpozi/currencyservice-worker:1.0.0
          image: jukpozi/currencyservice-worker:latest
          imagePullPolicy: Always
          env:
            - name: CURRENCYSERVICE_URL
              value: "http://currencyservice.core.svc.cluster.local:7000"
            - name: NERVE_CENTER_URL
              value: "http://nerve-center.core.svc.cluster.local:8080"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
