apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice-worker
  namespace: workers
spec:
  replicas: 0   # KEDA controls replicas
  selector:
    matchLabels:
      app: paymentservice-worker
  template:
    metadata:
      labels:
        app: paymentservice-worker
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: paymentservice-worker-sa
      containers:
        - name: paymentservice-worker
          # TODO: pin to a specific tag e.g. jukpozi/paymentservice-worker:1.0.0
          image: jukpozi/paymentservice-worker:latest
          imagePullPolicy: Always
          env:
            - name: PAYMENTSERVICE_URL
              value: "http://paymentservice.core.svc.cluster.local:50051"
            - name: NERVE_CENTER_URL
              value: "http://nerve-center.core.svc.cluster.local:8080"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
