name: recommendationservice
namespace: core

replicaCount: 1

image:
  repository: jukpozi/recommendationservice
  tag: latest
  pullPolicy: Always

serviceAccount:
  name: recommendationservice-sa

containerPort: 8080

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "512Mi"

env:
  - name: PORT
    value: "8080"
  - name: PRODUCT_CATALOG_SERVICE_ADDR
    value: "productcatalogservice.core.svc.cluster.local:3550"
  - name: ENABLE_TRACING
    value: "0"
  - name: ENABLE_PROFILER
    value: "0"
