apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice-worker
  namespace: workers
spec:
  replicas: 0   # KEDA controls replicas
  selector:
    matchLabels:
      app: recommendationservice-worker
  template:
    metadata:
      labels:
        app: recommendationservice-worker
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: recommendationservice-worker-sa
      containers:
        - name: recommendationservice-worker
          # TODO: pin to a specific tag e.g. jukpozi/recommendationservice-worker:1.0.0
          image: jukpozi/recommendationservice-worker:latest
          imagePullPolicy: Always
          env:
            - name: RECOMMENDATIONSERVICE_URL
              value: "http://recommendationservice.core.svc.cluster.local:8080"
            - name: NERVE_CENTER_URL
              value: "http://nerve-center.core.svc.cluster.local:8080"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
