name: cartservice
namespace: core

replicaCount: 1

image:
  repository: jukpozi/cartservice
  tag: latest
  pullPolicy: Always

serviceAccount:
  name: cartservice-sa

containerPort: 7070

service:
  type: ClusterIP
  port: 7070

resources:
  requests:
    cpu: "200m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

env:
  - name: ASPNETCORE_HTTP_PORTS
    value: "7070"
  - name: ENABLE_TRACING
    value: "0"
