environment: prod

location: eastus

rg_name: jd-core-rg-prod

network:
  vnet_cidr: "10.1.0.0/16"
  subnet_cidr: "10.1.0.0/22"

aks:
  cluster_name: "jd-aks-prod"
  vm_size: "Standard_D8ds_v5"
  node_min: 3
  node_max: 10
  service_cidr: "10.2.0.0/16"
  dns_service_ip: "10.2.0.10"

cosmos:
  throughput: 8000

servicebus:
  sku: "Standard"
