name: productcatalogservice
namespace: core

replicaCount: 1

image:
  repository: jukpozi/productcatalogservice
  tag: latest
  pullPolicy: Always

serviceAccount:
  name: productcatalogservice-sa
  clientId: "98224623-cf71-439e-b480-d726de30d10e"

containerPort: 3550

service:
  type: ClusterIP
  port: 3550

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

env:
  - name: PORT
    value: "3550"
  - name: ENABLE_TRACING
    value: "1"
  - name: ENABLE_PROFILER
    value: "0"
  - name: COLLECTOR_SERVICE_ADDR
    value: "otel-collector-opentelemetry-collector.observability.svc.cluster.local:4317"
  - name: OTEL_SERVICE_NAME
    value: "productcatalogservice"
  - name: COSMOS_ENDPOINT
    value: "https://sre-cosmos.documents.azure.com:443/"
  - name: COSMOS_DATABASE
    value: "product-catalog-db"
  - name: COSMOS_CONTAINER
    value: "products"
