apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice-worker
  namespace: workers
spec:
  replicas: 0   # KEDA controls replicas
  selector:
    matchLabels:
      app: checkoutservice-worker
  template:
    metadata:
      labels:
        app: checkoutservice-worker
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: checkoutservice-worker-sa
      containers:
        - name: checkoutservice-worker
          # TODO: pin to a specific tag e.g. jukpozi/checkoutservice-worker:1.0.0
          image: jukpozi/checkoutservice-worker:latest
          imagePullPolicy: Always
          env:
            - name: CHECKOUTSERVICE_URL
              value: "http://checkoutservice.core.svc.cluster.local:5050"
            - name: NERVE_CENTER_URL
              value: "http://nerve-center.core.svc.cluster.local:8080"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
