name: cartservice
namespace: core

replicaCount: 1

image:
  repository: jukpozi/cartservice
  tag: latest
  pullPolicy: Always

serviceAccount:
  name: cartservice-sa
  # Get this value from: terraform -chdir=terraform/environments/dev output worker_client_ids
  clientId: "546eacdf-f31f-4950-9319-73a6ce56713c"

containerPort: 7070

service:
  type: ClusterIP
  port: 7070

resources:
  requests:
    cpu: "200m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

env:
  - name: ASPNETCORE_HTTP_PORTS
    value: "7070"
  - name: ENABLE_TRACING
    value: "1"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://otel-collector-opentelemetry-collector.observability.svc.cluster.local:4317"
  - name: OTEL_SERVICE_NAME
    value: "cartservice"
  # Full StackExchange.Redis connection string stored in a K8s Secret.
  # Create the secret: kubectl create secret generic redis-secret \
  #   --namespace core \
  #   --from-literal=connectionString="sre-redis-cart.redis.cache.windows.net:6380,ssl=true,abortConnect=false,password=<ACCESS_KEY>"
  # Get ACCESS_KEY from: terraform -chdir=terraform/environments/dev output -raw redis_primary_key  (sensitive)
  - name: REDIS_ADDR
    valueFrom:
      secretKeyRef:
        name: redis-secret
        key: connectionString
