apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: currencyservice
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/jaeveloper/sre-proj-upgrade
    targetRevision: main
    path: helm/core-services/currencyservice

  destination:
    server: https://kubernetes.default.svc
    namespace: core

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
