apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: sre-platform

spec:
  project: default

  source:
    repoURL: https://kedacore.github.io/charts
    chart: keda
    targetRevision: "2.19.0"
    helm:
      values: |
        podIdentity:
          azureWorkload:
            enabled: true
            clientId: "7f612430-3643-4447-a0da-6a02f9dee0d0"
            tenantId: "215b7ce2-5263-4593-a622-da030405d151"

  destination:
    server: https://kubernetes.default.svc
    namespace: keda

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
