apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shipping-worker
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: sre-platform

spec:
  project: default

  source:
    repoURL: https://github.com/jaeveloper/sre-proj-upgrade
    targetRevision: main
    path: helm/workers/shipping-worker

  destination:
    server: https://kubernetes.default.svc
    namespace: workers

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
