name: frontend
namespace: core

replicaCount: 1

image:
  repository: jukpozi/frontend
  tag: latest
  pullPolicy: Always

serviceAccount:
  name: frontend-sa

containerPort: 8080

service:
  type: LoadBalancer
  port: 80

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

env:
  - name: PRODUCT_CATALOG_SERVICE_ADDR
    value: "productcatalogservice.core.svc.cluster.local:3550"
  - name: CURRENCY_SERVICE_ADDR
    value: "currencyservice.core.svc.cluster.local:7000"
  - name: CART_SERVICE_ADDR
    value: "cartservice.core.svc.cluster.local:7070"
  - name: RECOMMENDATION_SERVICE_ADDR
    value: "recommendationservice.core.svc.cluster.local:8080"
  - name: CHECKOUT_SERVICE_ADDR
    value: "checkoutservice.core.svc.cluster.local:5050"
  - name: SHIPPING_SERVICE_ADDR
    value: "shippingservice.core.svc.cluster.local:50051"
  - name: AD_SERVICE_ADDR
    value: "adservice.core.svc.cluster.local:9555"
  - name: SHOPPING_ASSISTANT_SERVICE_ADDR
    value: "shoppingassistantservice.core.svc.cluster.local:8080"
  - name: ENV_PLATFORM
    value: "azure"
  - name: ENABLE_TRACING
    value: "1"
  - name: ENABLE_PROFILER
    value: "0"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://otel-collector.observability.svc.cluster.local:4317"
  - name: OTEL_SERVICE_NAME
    value: "frontend"
