name: payment-worker
namespace: workers

image:
  repository: jukpozi/paymentservice
  tag: latest
  pullPolicy: Always

serviceAccount:
  name: paymentservice-worker-sa
  clientId: "b023641f-3f8a-45b0-a768-81cd63548666"

env:
  - name: WORKER_MODE
    value: "true"
  - name: SERVICEBUS_NAMESPACE
    value: "sre-sb-namespace"
  - name: SERVICEBUS_TOPIC
    value: "checkout-events"
  - name: SERVICEBUS_SUBSCRIPTION
    value: "payment"
  - name: DISABLE_PROFILER
    value: "1"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://otel-collector.observability.svc.cluster.local:4317"
  - name: OTEL_SERVICE_NAME
    value: "payment-worker"

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

keda:
  serviceBusNamespace: sre-sb-namespace
  topicName: checkout-events
  subscriptionName: payment
  messageCount: "1"
  pollingInterval: 10
  cooldownPeriod: 60
  minReplicaCount: 0
  maxReplicaCount: 15
