name: emailservice
namespace: core

replicaCount: 1

image:
  repository: jukpozi/emailservice
  tag: latest
  pullPolicy: Always

serviceAccount:
  name: emailservice-sa

containerPort: 5000

service:
  type: ClusterIP
  port: 5000

resources:
  requests:
    cpu: "100m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

env:
  - name: PORT
    value: "5000"
  - name: DISABLE_TRACING
    value: "0"
  - name: DISABLE_PROFILER
    value: "1"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://otel-collector-opentelemetry-collector.observability.svc.cluster.local:4317"
  - name: OTEL_SERVICE_NAME
    value: "emailservice"
