name: checkoutservice
namespace: core

replicaCount: 1

image:
  repository: jukpozi/checkoutservice
  tag: latest
  pullPolicy: Always

serviceAccount:
  name: checkoutservice-sa
  clientId: "0744a964-44cb-470d-976c-0251afd3db83"

containerPort: 5050

service:
  type: ClusterIP
  port: 5050

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

env:
  - name: PORT
    value: "5050"
  - name: PRODUCT_CATALOG_SERVICE_ADDR
    value: "productcatalogservice.core.svc.cluster.local:3550"
  - name: CART_SERVICE_ADDR
    value: "cartservice.core.svc.cluster.local:7070"
  - name: CURRENCY_SERVICE_ADDR
    value: "currencyservice.core.svc.cluster.local:7000"
  - name: SHIPPING_SERVICE_ADDR
    value: "shippingservice.core.svc.cluster.local:50051"
  - name: EMAIL_SERVICE_ADDR
    value: "emailservice.core.svc.cluster.local:5000"
  - name: PAYMENT_SERVICE_ADDR
    value: "paymentservice.core.svc.cluster.local:50051"
  - name: ENABLE_EVENT_PUBLISHING
    value: "1"
  - name: SERVICEBUS_NAMESPACE
    value: "sre-sb-namespace"
  - name: SERVICEBUS_TOPIC
    value: "checkout-events"
  - name: AZURE_CLIENT_ID
    value: "0744a964-44cb-470d-976c-0251afd3db83"
  - name: ENABLE_TRACING
    value: "1"
  - name: ENABLE_PROFILER
    value: "0"
  - name: COLLECTOR_SERVICE_ADDR
    value: "otel-collector-opentelemetry-collector.observability.svc.cluster.local:4317"
  - name: OTEL_SERVICE_NAME
    value: "checkoutservice"
