environment: dev

location: westus2

rg_name: jd-core-rg

network:
  vnet_cidr: "10.0.0.0/16"
  subnet_cidr: "10.0.0.0/22"

aks:
  cluster_name: "jd-aks"
  vm_size: "Standard_D2s_v5"      # B4als_v2 + D2s_v3 + B4ms + B4as_v2 all CapacityRestricted in westus2
  node_min: 1
  node_max: 3
  user_vm_size: "Standard_D2s_v5"
  user_node_min: 1
  user_node_max: 3
  service_cidr: "10.1.0.0/16"
  dns_service_ip: "10.1.0.10"

cosmos:
  throughput: 4000

servicebus:
  sku: "Standard"
